[build]
  # Override UI settings - skip build since files are pre-built
  command = ""
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
